name: Test reusable action
on:
  workflow_call:
    inputs:
      var1:
        type: string
        required: true
        default: 123

env:
  VAR1: ${{ inputs.var1 }}

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: app
      - uses: actions/checkout@v4
        with:
          path: local
          repository: hangarlabsnet/gha-test@main
      - run: echo "Hello! "$VAR1
      - run: ls -la
      - run: ls -la app
      - run: ls -la local
      - run: env
